---
title: "classwork-Thurs-3-9.Rmd"
author: "Jin Sun Kim"
date: "March 9, 2017"
output: html_document
---

```{r}
library(ggplot2)
canid_occ <- ggplot(canids, aes( species, ymin = maxage, ymax=minage+0.5, colour = genus))
canid_occ <- canid_occ + geom_linerange()
canid_occ <- canid_occ + theme(legend.position="none")
canid_occ <- canid_occ + coord_flip()
canid_occ <- canid_occ +  theme(axis.text.y = element_text(size=3))
canid_occ <- canid_occ + theme(axis.ticks.y=element_blank())
canid_occ <- canid_occ + scale_y_continuous(limits=c(0, 40), expand = c(0, 0), breaks=c(0, 10, 20, 30, 40))
canid_occ <- canid_occ + labs(title = "Canid Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20))
# the ones where minage and maxage is same is shown as a point
```

```{r}
library(forcats)

canid_occ <- ggplot(canids, aes( x = fct_reorder(species, minage, .desc = T), maxage, colour = genus))
anid_occ <- canid_occ + geom_linerange()
canid_occ <- canid_occ + theme(legend.position="none")
canid_occ <- canid_occ + coord_flip()
canid_occ <- canid_occ +  theme(axis.text.y = element_text(size=3))
canid_occ <- canid_occ + theme(axis.ticks.y=element_blank())
canid_occ <- canid_occ + scale_y_continuous(limits=c(0, 40), expand = c(0, 0), breaks=c(0, 10, 20, 30, 40))
canid_occ <- canid_occ + labs(title = "faceted Canid Fossil Occurrences", x = "Species", y = "Ma ago") + theme(plot.title = element_text(hjust = 0.5, size=22, face = "bold"), axis.title =element_text(size=20))

```

```{r}
diversity <- canids %>% gather(key = type, value = age, minage, maxage)

head(diversity)

```
